### ISSUE TITLE
Milestones, workload distribution

### ISSUE THREAD

**Issue by fouweric** [patceline/wikileaks-data-analytics#1]
Following our [Project Proposal][pp], we should create here
- [ ] Milestones
- [ ] Issues
- [ ] Attribute these issues to people

in order to start the work asap.

[pp]: https://docs.google.com/document/d/1Rt_N2XSz32y1PYaXiwmkHtMdoBA12iGWu1YdpNn1Yu4/edit?usp=sharing

**Comment by fouweric** [comment]
@patceline You are the one assigned to the task, but of course, this should be solved in a common effort ;)
Do you have any wishes on how to organize milestones/issues?
Furthermore, should our TA be part of this github repo?

**Comment by agulfy** [comment]
> Furthermore, should our TA be part of this github repo? 
I think an invite won't hurt

Since there was no movement on writing milestones, I proposed some milestones/deadlines at the wiki. I had us diplomacy dataset in my mind while writing these deadlines - and assumed that the majority of the students will start working on this dataset after 14 April when War Diaries aggregations are completed and we move on to the "third part". Any opinions?

31 March: Finish looking for new datasets, get familiar with the data itself. Upload the data to the cluster, import into a database with meaningful attributes.
14 April: Have a simple back-end to communicate with data - do "simple" aggregations
(Tasks up to this point will be very similar to the team members working on the War diaries)
28 April: Experiment with more advanced analysis tools/NLP
12 May: Complete visualization, report

**Comment by patceline** [comment]
Hey, thanks for this! I think it's good, but I do think we should try to be done with the first point sooner (we should at least try). Maybe march 24? This gives us 2 weeks. Then we can have more time for the other tasks

**Comment by agulfy** [comment]
March 24 could work as long as we assign tasks asap (until this weekend?).
War diaries group needs to do some crawling to get the data if I remember correcly- that's why I postponed the deadline a little.

**Comment by fouweric** [comment]
Cool Plan :+1: 
We can extend the milestone if needed :=)
